[package]
name = "server-with-unikraft"
version = "0.1.0"
authors = ["ubuntu"]
edition = "2018"

[dependencies]
hyper = { version = "0.14", features = ["full"]}
tokio = { version = "1", features = ["rt", "macros", "net", "time", "io-util"]}
