# syntax=docker/dockerfile:1

FROM --platform=$BUILDPLATFORM rust:1.83 AS buildbase
WORKDIR /src
RUN <<EOT bash
    set -ex
    apt-get update
    apt-get install -y \
        git \
        clang
EOT

FROM buildbase AS build
COPY Cargo.toml .
COPY src ./src 
# Build the binary
RUN cargo build --release

FROM scratch
ENTRYPOINT [ "/server-without-wasm" ]
COPY --from=build /src/target/release/server-without-wasm /server-without-wasm
